---
name: Update all Puppet modules

on:
  workflow_dispatch: {}
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  msync:
    runs-on: ubuntu-latest
    name: Run msync against all modules
    steps:
      - name: checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: ${{ github.ref }}
      - name: describe
        run: git describe
