name: duffy
on:
  workflow_dispatch:

jobs:

  duffy:
    name: duffy
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      duffy:
        image: quay.io/evgeni/duffy-mock:latest
        ports:
          - 8080:8080
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install duffy[client]
      - run: duffy client --url http://localhost:8080/api/v1 --auth-name tenant123 --auth-key 3e9bccb1-20cf-46be-963a-7091b3812646 list-pools
      - run: duffy client --url http://localhost:8080/api/v1 --auth-name tenant123 --auth-key 3e9bccb1-20cf-46be-963a-7091b3812646 list-sessions
      - run: duffy client --url http://localhost:8080/api/v1 --auth-name tenant123 --auth-key 3e9bccb1-20cf-46be-963a-7091b3812646 request-session pool=physical-centos8stream-x86_64,quantity=1
      - run: duffy client --url http://localhost:8080/api/v1 --auth-name tenant123 --auth-key 3e9bccb1-20cf-46be-963a-7091b3812646 list-sessions
