name: Report

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  report:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Download metadata artifact'
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/download_workflow_run_artifact.js');
            let fs = require('fs');
            await script({github, context, core, fs, artifact_name: 'pr'});

      - name: 'Unzip artifact'
        run: unzip pr.zip

      - name: Read PR data
        run: echo "PR_DATA=$(cat ./pr.json)" >> $GITHUB_ENV

      - name: 'Download other artifacts'
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/download_workflow_run_artifact.js');
            let fs = require('fs');
            await script({github, context, core, fs, artifact_name: 'foreman-docs-html-${{ fromJSON(env.PR_DATA).branch_name }}'});
            await script({github, context, core, fs, artifact_name: 'foreman-docs-web-master'});

      - name: list
        run: ls -alh

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ fromJSON(env.PR_DATA).pr_number }}
          message: 'Comment from a workflow for PR ${{ fromJSON(env.PR_DATA).pr_number }} for ${{ fromJSON(env.PR_DATA).head_sha }}'
