name: Report

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  report:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr_number"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr_number.zip`, Buffer.from(download.data));

      - name: 'Unzip artifact'
        run: unzip pr_number.zip

      - name: Read PR data
        run: echo "PR_DATA=$(cat ./pr.json)" >> $GITHUB_ENV
      - run: echo ${{ github.event.workflow_run.conclusion }}
      - run: echo '${{ toJSON(github.event.workflow_run) }}'
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ fromJSON(env.PR_DATA).pr_number }}
          message: 'Comment from a workflow for PR ${{ fromJSON(env.PR_DATA).pr_number }} for ${{ fromJSON(env.PR_DATA).head_sha }}'
