name: Report

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  report:
    if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          debug: true
          script: |
            const script = require('./.github/download_workflow_run_artifact.js');
            let fs = require('fs');
            await script({github, context, core, fs});

      - name: 'Unzip artifact'
        run: unzip pr_number.zip

      - name: Read PR data
        run: echo "PR_DATA=$(cat ./pr.json)" >> $GITHUB_ENV
      - run: echo ${{ github.event.workflow_run.conclusion }}
      - run: echo '${{ toJSON(github.event.workflow_run) }}'
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{ fromJSON(env.PR_DATA).pr_number }}
          message: 'Comment from a workflow for PR ${{ fromJSON(env.PR_DATA).pr_number }} for ${{ fromJSON(env.PR_DATA).head_sha }}'
