name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: install rpm packages
        run: sudo apt-get install -y rpm python3-rpm
      - name: crude rpm so hack
        run: |
          export basedir=/usr/lib/python3/dist-packages/rpm
          for file in ${basedir}/_rpm*.cpython-*.so;
            do sudo ln -s ${file} $(echo ${file} | sed 's/\.cpython[^.]*//');
          done
      - name: install rpm-shim
        run: pip install --upgrade rpm
      - name: run tests
        run: python rpmtest.py
