name: Update packages

on:
  workflow_dispatch:

env:
  GIT_AUTHOR_NAME: Foreman Packaging Automation
  GIT_AUTHOR_EMAIL: packaging@theforeman.org

jobs:

  report:
    name: Report failure to Discourse
    runs-on: ubuntu-latest
    steps:
    - name: Send email to Discourse on failure
      run: echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - name: Send email to Discourse on failure
      run: echo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
