name: Test

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - run: command -v chrome-browser || true
      - run: command -v chromium-browser || true
      - run: command -v chromedriver || true
      - run: chromium-browser --version
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome
        with:
          chrome-version: '120.0.6099.109'
      - run: |
          sudo rm -f /usr/bin/chromium-browser
          sudo ln -s ${{ steps.setup-chrome.outputs.chrome-path }} /usr/bin/chromium-browser
      - run: command -v chrome-browser || true
      - run: command -v chromium-browser || true
      - run: command -v chromedriver || true
      - run: chromium-browser --version
      - run: chromedriver --version
      - run: dpkg -L google-chrome-stable |grep bin
