name: Test

on:
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name (pull request)
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV

      - name: Generate fake artifact
        run: |
          mkdir lol
          echo lol > lol/lol

      - name: Upload HTML
        uses: actions/upload-artifact@v2
        with:
          name: foreman-docs-html-${{ env.BRANCH_NAME }}
          path: lol

      - name: Upload web
        uses: actions/upload-artifact@v2
        with:
          name: foreman-docs-web-master
          path: lol

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo '{"pr_number": ${{ github.event.number }}, "branch_name": "${{ env.BRANCH_NAME }}", "head_sha": "${{ github.event.pull_request.head.sha }}"}' > ./pr/pr.json

      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/
